use_frameworks!

platform :ios, '12.0'

target 'FANBaseConfig_Example' do
  pod 'FANBaseConfig', :path => '../'
  
  pod 'SnapKit'

  target 'FANBaseConfig_Tests' do
    inherit! :search_paths
    
    
  end
  
#  post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    end
#  end

end
