use_frameworks!

platform :ios, '12.0'

target 'FANBaseConfig_Example' do
  pod 'FANBaseConfig', :path => '../'
  
  pod 'SnapKit'

  target 'FANBaseConfig_Tests' do
    inherit! :search_paths
    
    
  end
end
